//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class AccountDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentSkinIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CurrentSkinUnlockedIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasProfilePhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Coins {
            get {
                return this.CoinsField;
            }
            set {
                if ((this.CoinsField.Equals(value) != true)) {
                    this.CoinsField = value;
                    this.RaisePropertyChanged("Coins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentSkinId {
            get {
                return this.CurrentSkinIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentSkinIdField, value) != true)) {
                    this.CurrentSkinIdField = value;
                    this.RaisePropertyChanged("CurrentSkinId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CurrentSkinUnlockedId {
            get {
                return this.CurrentSkinUnlockedIdField;
            }
            set {
                if ((this.CurrentSkinUnlockedIdField.Equals(value) != true)) {
                    this.CurrentSkinUnlockedIdField = value;
                    this.RaisePropertyChanged("CurrentSkinUnlockedId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasProfilePhoto {
            get {
                return this.HasProfilePhotoField;
            }
            set {
                if ((this.HasProfilePhotoField.Equals(value) != true)) {
                    this.HasProfilePhotoField = value;
                    this.RaisePropertyChanged("HasProfilePhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileDescription {
            get {
                return this.ProfileDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDescriptionField, value) != true)) {
                    this.ProfileDescriptionField = value;
                    this.RaisePropertyChanged("ProfileDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePhotoId {
            get {
                return this.ProfilePhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePhotoIdField, value) != true)) {
                    this.ProfilePhotoIdField = value;
                    this.RaisePropertyChanged("ProfilePhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfilePhotoDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class ProfilePhotoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePhotoId {
            get {
                return this.ProfilePhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePhotoIdField, value) != true)) {
                    this.ProfilePhotoIdField = value;
                    this.RaisePropertyChanged("ProfilePhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProfileRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class UpdateProfileRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileDescription {
            get {
                return this.ProfileDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileDescriptionField, value) != true)) {
                    this.ProfileDescriptionField = value;
                    this.RaisePropertyChanged("ProfileDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePhotoId {
            get {
                return this.ProfilePhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePhotoIdField, value) != true)) {
                    this.ProfilePhotoIdField = value;
                    this.RaisePropertyChanged("ProfilePhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarProfileOptionsDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class AvatarProfileOptionsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionDto[] AvatarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionDto[] Avatars {
            get {
                return this.AvatarsField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarsField, value) != true)) {
                    this.AvatarsField = value;
                    this.RaisePropertyChanged("Avatars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarProfileOptionDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class AvatarProfileOptionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUnlockedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarCode {
            get {
                return this.AvatarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarCodeField, value) != true)) {
                    this.AvatarCodeField = value;
                    this.RaisePropertyChanged("AvatarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnlocked {
            get {
                return this.IsUnlockedField;
            }
            set {
                if ((this.IsUnlockedField.Equals(value) != true)) {
                    this.IsUnlockedField = value;
                    this.RaisePropertyChanged("IsUnlocked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarSelectionRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class AvatarSelectionRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarCode {
            get {
                return this.AvatarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarCodeField, value) != true)) {
                    this.AvatarCodeField = value;
                    this.RaisePropertyChanged("AvatarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetProfileByUsername", ReplyAction="http://tempuri.org/IUserService/GetProfileByUsernameResponse")]
        SnakeAndLaddersFinalProject.UserService.AccountDto GetProfileByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetProfileByUsername", ReplyAction="http://tempuri.org/IUserService/GetProfileByUsernameResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> GetProfileByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetProfilePhoto", ReplyAction="http://tempuri.org/IUserService/GetProfilePhotoResponse")]
        SnakeAndLaddersFinalProject.UserService.ProfilePhotoDto GetProfilePhoto(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetProfilePhoto", ReplyAction="http://tempuri.org/IUserService/GetProfilePhotoResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.ProfilePhotoDto> GetProfilePhotoAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        SnakeAndLaddersFinalProject.UserService.AccountDto UpdateProfile(SnakeAndLaddersFinalProject.UserService.UpdateProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateProfile", ReplyAction="http://tempuri.org/IUserService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> UpdateProfileAsync(SnakeAndLaddersFinalProject.UserService.UpdateProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeactivateAccount", ReplyAction="http://tempuri.org/IUserService/DeactivateAccountResponse")]
        void DeactivateAccount(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeactivateAccount", ReplyAction="http://tempuri.org/IUserService/DeactivateAccountResponse")]
        System.Threading.Tasks.Task DeactivateAccountAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAvatarOptions", ReplyAction="http://tempuri.org/IUserService/GetAvatarOptionsResponse")]
        SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionsDto GetAvatarOptions(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAvatarOptions", ReplyAction="http://tempuri.org/IUserService/GetAvatarOptionsResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionsDto> GetAvatarOptionsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SelectAvatarForProfile", ReplyAction="http://tempuri.org/IUserService/SelectAvatarForProfileResponse")]
        SnakeAndLaddersFinalProject.UserService.AccountDto SelectAvatarForProfile(SnakeAndLaddersFinalProject.UserService.AvatarSelectionRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SelectAvatarForProfile", ReplyAction="http://tempuri.org/IUserService/SelectAvatarForProfileResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> SelectAvatarForProfileAsync(SnakeAndLaddersFinalProject.UserService.AvatarSelectionRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : SnakeAndLaddersFinalProject.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.UserService.IUserService>, SnakeAndLaddersFinalProject.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.UserService.AccountDto GetProfileByUsername(string username) {
            return base.Channel.GetProfileByUsername(username);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> GetProfileByUsernameAsync(string username) {
            return base.Channel.GetProfileByUsernameAsync(username);
        }
        
        public SnakeAndLaddersFinalProject.UserService.ProfilePhotoDto GetProfilePhoto(int userId) {
            return base.Channel.GetProfilePhoto(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.ProfilePhotoDto> GetProfilePhotoAsync(int userId) {
            return base.Channel.GetProfilePhotoAsync(userId);
        }
        
        public SnakeAndLaddersFinalProject.UserService.AccountDto UpdateProfile(SnakeAndLaddersFinalProject.UserService.UpdateProfileRequestDto request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> UpdateProfileAsync(SnakeAndLaddersFinalProject.UserService.UpdateProfileRequestDto request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public void DeactivateAccount(int userId) {
            base.Channel.DeactivateAccount(userId);
        }
        
        public System.Threading.Tasks.Task DeactivateAccountAsync(int userId) {
            return base.Channel.DeactivateAccountAsync(userId);
        }
        
        public SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionsDto GetAvatarOptions(int userId) {
            return base.Channel.GetAvatarOptions(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AvatarProfileOptionsDto> GetAvatarOptionsAsync(int userId) {
            return base.Channel.GetAvatarOptionsAsync(userId);
        }
        
        public SnakeAndLaddersFinalProject.UserService.AccountDto SelectAvatarForProfile(SnakeAndLaddersFinalProject.UserService.AvatarSelectionRequestDto request) {
            return base.Channel.SelectAvatarForProfile(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.UserService.AccountDto> SelectAvatarForProfileAsync(SnakeAndLaddersFinalProject.UserService.AvatarSelectionRequestDto request) {
            return base.Channel.SelectAvatarForProfileAsync(request);
        }
    }
}
