//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.SocialProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialProfileDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class SocialProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType NetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType Network {
            get {
                return this.NetworkField;
            }
            set {
                if ((this.NetworkField.Equals(value) != true)) {
                    this.NetworkField = value;
                    this.RaisePropertyChanged("Network");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileLink {
            get {
                return this.ProfileLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileLinkField, value) != true)) {
                    this.ProfileLinkField = value;
                    this.RaisePropertyChanged("ProfileLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkType", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Enums")]
    public enum SocialNetworkType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Instagram = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facebook = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twitter = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkSocialProfileRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class LinkSocialProfileRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType NetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType Network {
            get {
                return this.NetworkField;
            }
            set {
                if ((this.NetworkField.Equals(value) != true)) {
                    this.NetworkField = value;
                    this.RaisePropertyChanged("Network");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileLink {
            get {
                return this.ProfileLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileLinkField, value) != true)) {
                    this.ProfileLinkField = value;
                    this.RaisePropertyChanged("ProfileLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnlinkSocialProfileRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class UnlinkSocialProfileRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType NetworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.SocialProfileService.SocialNetworkType Network {
            get {
                return this.NetworkField;
            }
            set {
                if ((this.NetworkField.Equals(value) != true)) {
                    this.NetworkField = value;
                    this.RaisePropertyChanged("Network");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialProfileService.ISocialProfileService")]
    public interface ISocialProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/GetSocialProfiles", ReplyAction="http://tempuri.org/ISocialProfileService/GetSocialProfilesResponse")]
        SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto[] GetSocialProfiles(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/GetSocialProfiles", ReplyAction="http://tempuri.org/ISocialProfileService/GetSocialProfilesResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto[]> GetSocialProfilesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/LinkSocialProfile", ReplyAction="http://tempuri.org/ISocialProfileService/LinkSocialProfileResponse")]
        SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto LinkSocialProfile(SnakeAndLaddersFinalProject.SocialProfileService.LinkSocialProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/LinkSocialProfile", ReplyAction="http://tempuri.org/ISocialProfileService/LinkSocialProfileResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto> LinkSocialProfileAsync(SnakeAndLaddersFinalProject.SocialProfileService.LinkSocialProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/UnlinkSocialProfile", ReplyAction="http://tempuri.org/ISocialProfileService/UnlinkSocialProfileResponse")]
        void UnlinkSocialProfile(SnakeAndLaddersFinalProject.SocialProfileService.UnlinkSocialProfileRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialProfileService/UnlinkSocialProfile", ReplyAction="http://tempuri.org/ISocialProfileService/UnlinkSocialProfileResponse")]
        System.Threading.Tasks.Task UnlinkSocialProfileAsync(SnakeAndLaddersFinalProject.SocialProfileService.UnlinkSocialProfileRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialProfileServiceChannel : SnakeAndLaddersFinalProject.SocialProfileService.ISocialProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialProfileServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.SocialProfileService.ISocialProfileService>, SnakeAndLaddersFinalProject.SocialProfileService.ISocialProfileService {
        
        public SocialProfileServiceClient() {
        }
        
        public SocialProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto[] GetSocialProfiles(int userId) {
            return base.Channel.GetSocialProfiles(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto[]> GetSocialProfilesAsync(int userId) {
            return base.Channel.GetSocialProfilesAsync(userId);
        }
        
        public SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto LinkSocialProfile(SnakeAndLaddersFinalProject.SocialProfileService.LinkSocialProfileRequestDto request) {
            return base.Channel.LinkSocialProfile(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.SocialProfileService.SocialProfileDto> LinkSocialProfileAsync(SnakeAndLaddersFinalProject.SocialProfileService.LinkSocialProfileRequestDto request) {
            return base.Channel.LinkSocialProfileAsync(request);
        }
        
        public void UnlinkSocialProfile(SnakeAndLaddersFinalProject.SocialProfileService.UnlinkSocialProfileRequestDto request) {
            base.Channel.UnlinkSocialProfile(request);
        }
        
        public System.Threading.Tasks.Task UnlinkSocialProfileAsync(SnakeAndLaddersFinalProject.SocialProfileService.UnlinkSocialProfileRequestDto request) {
            return base.Channel.UnlinkSocialProfileAsync(request);
        }
    }
}
