//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.PlayerReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class ReportDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReportedUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReporterUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportReason {
            get {
                return this.ReportReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReasonField, value) != true)) {
                    this.ReportReasonField = value;
                    this.RaisePropertyChanged("ReportReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportedUserId {
            get {
                return this.ReportedUserIdField;
            }
            set {
                if ((this.ReportedUserIdField.Equals(value) != true)) {
                    this.ReportedUserIdField = value;
                    this.RaisePropertyChanged("ReportedUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReporterUserId {
            get {
                return this.ReporterUserIdField;
            }
            set {
                if ((this.ReporterUserIdField.Equals(value) != true)) {
                    this.ReporterUserIdField = value;
                    this.RaisePropertyChanged("ReporterUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BanInfoDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class BanInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BanEndsAtUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SanctionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BanEndsAtUtc {
            get {
                return this.BanEndsAtUtcField;
            }
            set {
                if ((this.BanEndsAtUtcField.Equals(value) != true)) {
                    this.BanEndsAtUtcField = value;
                    this.RaisePropertyChanged("BanEndsAtUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBanned {
            get {
                return this.IsBannedField;
            }
            set {
                if ((this.IsBannedField.Equals(value) != true)) {
                    this.IsBannedField = value;
                    this.RaisePropertyChanged("IsBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SanctionType {
            get {
                return this.SanctionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SanctionTypeField, value) != true)) {
                    this.SanctionTypeField = value;
                    this.RaisePropertyChanged("SanctionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanctionDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class SanctionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AppliedBySystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SanctionDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SanctionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SanctionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AppliedBySystem {
            get {
                return this.AppliedBySystemField;
            }
            set {
                if ((this.AppliedBySystemField.Equals(value) != true)) {
                    this.AppliedBySystemField = value;
                    this.RaisePropertyChanged("AppliedBySystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportReason {
            get {
                return this.ReportReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReasonField, value) != true)) {
                    this.ReportReasonField = value;
                    this.RaisePropertyChanged("ReportReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SanctionDateUtc {
            get {
                return this.SanctionDateUtcField;
            }
            set {
                if ((this.SanctionDateUtcField.Equals(value) != true)) {
                    this.SanctionDateUtcField = value;
                    this.RaisePropertyChanged("SanctionDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SanctionId {
            get {
                return this.SanctionIdField;
            }
            set {
                if ((this.SanctionIdField.Equals(value) != true)) {
                    this.SanctionIdField = value;
                    this.RaisePropertyChanged("SanctionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SanctionType {
            get {
                return this.SanctionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SanctionTypeField, value) != true)) {
                    this.SanctionTypeField = value;
                    this.RaisePropertyChanged("SanctionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuickKickDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class QuickKickDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HostUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KickReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HostUserId {
            get {
                return this.HostUserIdField;
            }
            set {
                if ((this.HostUserIdField.Equals(value) != true)) {
                    this.HostUserIdField = value;
                    this.RaisePropertyChanged("HostUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KickReason {
            get {
                return this.KickReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.KickReasonField, value) != true)) {
                    this.KickReasonField = value;
                    this.RaisePropertyChanged("KickReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetUserId {
            get {
                return this.TargetUserIdField;
            }
            set {
                if ((this.TargetUserIdField.Equals(value) != true)) {
                    this.TargetUserIdField = value;
                    this.RaisePropertyChanged("TargetUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerReportService.IPlayerReportService")]
    public interface IPlayerReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/CreateReport", ReplyAction="http://tempuri.org/IPlayerReportService/CreateReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SnakeAndLaddersFinalProject.PlayerReportService.ServiceFault), Action="http://tempuri.org/IPlayerReportService/CreateReportServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Faults")]
        void CreateReport(SnakeAndLaddersFinalProject.PlayerReportService.ReportDto report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/CreateReport", ReplyAction="http://tempuri.org/IPlayerReportService/CreateReportResponse")]
        System.Threading.Tasks.Task CreateReportAsync(SnakeAndLaddersFinalProject.PlayerReportService.ReportDto report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/GetCurrentBan", ReplyAction="http://tempuri.org/IPlayerReportService/GetCurrentBanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SnakeAndLaddersFinalProject.PlayerReportService.ServiceFault), Action="http://tempuri.org/IPlayerReportService/GetCurrentBanServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Faults")]
        SnakeAndLaddersFinalProject.PlayerReportService.BanInfoDto GetCurrentBan(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/GetCurrentBan", ReplyAction="http://tempuri.org/IPlayerReportService/GetCurrentBanResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.PlayerReportService.BanInfoDto> GetCurrentBanAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/GetSanctionsHistory", ReplyAction="http://tempuri.org/IPlayerReportService/GetSanctionsHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SnakeAndLaddersFinalProject.PlayerReportService.ServiceFault), Action="http://tempuri.org/IPlayerReportService/GetSanctionsHistoryServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Faults")]
        SnakeAndLaddersFinalProject.PlayerReportService.SanctionDto[] GetSanctionsHistory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/GetSanctionsHistory", ReplyAction="http://tempuri.org/IPlayerReportService/GetSanctionsHistoryResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.PlayerReportService.SanctionDto[]> GetSanctionsHistoryAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/QuickKickPlayer", ReplyAction="http://tempuri.org/IPlayerReportService/QuickKickPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SnakeAndLaddersFinalProject.PlayerReportService.ServiceFault), Action="http://tempuri.org/IPlayerReportService/QuickKickPlayerServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Faults")]
        void QuickKickPlayer(SnakeAndLaddersFinalProject.PlayerReportService.QuickKickDto quickKick);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerReportService/QuickKickPlayer", ReplyAction="http://tempuri.org/IPlayerReportService/QuickKickPlayerResponse")]
        System.Threading.Tasks.Task QuickKickPlayerAsync(SnakeAndLaddersFinalProject.PlayerReportService.QuickKickDto quickKick);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerReportServiceChannel : SnakeAndLaddersFinalProject.PlayerReportService.IPlayerReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerReportServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.PlayerReportService.IPlayerReportService>, SnakeAndLaddersFinalProject.PlayerReportService.IPlayerReportService {
        
        public PlayerReportServiceClient() {
        }
        
        public PlayerReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateReport(SnakeAndLaddersFinalProject.PlayerReportService.ReportDto report) {
            base.Channel.CreateReport(report);
        }
        
        public System.Threading.Tasks.Task CreateReportAsync(SnakeAndLaddersFinalProject.PlayerReportService.ReportDto report) {
            return base.Channel.CreateReportAsync(report);
        }
        
        public SnakeAndLaddersFinalProject.PlayerReportService.BanInfoDto GetCurrentBan(int userId) {
            return base.Channel.GetCurrentBan(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.PlayerReportService.BanInfoDto> GetCurrentBanAsync(int userId) {
            return base.Channel.GetCurrentBanAsync(userId);
        }
        
        public SnakeAndLaddersFinalProject.PlayerReportService.SanctionDto[] GetSanctionsHistory(int userId) {
            return base.Channel.GetSanctionsHistory(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.PlayerReportService.SanctionDto[]> GetSanctionsHistoryAsync(int userId) {
            return base.Channel.GetSanctionsHistoryAsync(userId);
        }
        
        public void QuickKickPlayer(SnakeAndLaddersFinalProject.PlayerReportService.QuickKickDto quickKick) {
            base.Channel.QuickKickPlayer(quickKick);
        }
        
        public System.Threading.Tasks.Task QuickKickPlayerAsync(SnakeAndLaddersFinalProject.PlayerReportService.QuickKickDto quickKick) {
            return base.Channel.QuickKickPlayerAsync(quickKick);
        }
    }
}
