//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.GameplayService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RollDiceRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class RollDiceRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentCellIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CurrentCellIndex {
            get {
                return this.CurrentCellIndexField;
            }
            set {
                if ((this.CurrentCellIndexField.Equals(value) != true)) {
                    this.CurrentCellIndexField = value;
                    this.RaisePropertyChanged("CurrentCellIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RollDiceResponseDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class RollDiceResponseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailureReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromCellIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToCellIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameplayService.MoveEffectType MoveResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameplayService.TokenStateDto[] UpdatedTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FailureReason {
            get {
                return this.FailureReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureReasonField, value) != true)) {
                    this.FailureReasonField = value;
                    this.RaisePropertyChanged("FailureReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int FromCellIndex {
            get {
                return this.FromCellIndexField;
            }
            set {
                if ((this.FromCellIndexField.Equals(value) != true)) {
                    this.FromCellIndexField = value;
                    this.RaisePropertyChanged("FromCellIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ToCellIndex {
            get {
                return this.ToCellIndexField;
            }
            set {
                if ((this.ToCellIndexField.Equals(value) != true)) {
                    this.ToCellIndexField = value;
                    this.RaisePropertyChanged("ToCellIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int DiceValue {
            get {
                return this.DiceValueField;
            }
            set {
                if ((this.DiceValueField.Equals(value) != true)) {
                    this.DiceValueField = value;
                    this.RaisePropertyChanged("DiceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public SnakeAndLaddersFinalProject.GameplayService.MoveEffectType MoveResult {
            get {
                return this.MoveResultField;
            }
            set {
                if ((this.MoveResultField.Equals(value) != true)) {
                    this.MoveResultField = value;
                    this.RaisePropertyChanged("MoveResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public SnakeAndLaddersFinalProject.GameplayService.TokenStateDto[] UpdatedTokens {
            get {
                return this.UpdatedTokensField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedTokensField, value) != true)) {
                    this.UpdatedTokensField = value;
                    this.RaisePropertyChanged("UpdatedTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ExtraInfo {
            get {
                return this.ExtraInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraInfoField, value) != true)) {
                    this.ExtraInfoField = value;
                    this.RaisePropertyChanged("ExtraInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveEffectType", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Enums")]
    public enum MoveEffectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Snake = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ladder = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bonus = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trap = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Teleport = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenStateDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class TokenStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CellIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CellIndex {
            get {
                return this.CellIndexField;
            }
            set {
                if ((this.CellIndexField.Equals(value) != true)) {
                    this.CellIndexField = value;
                    this.RaisePropertyChanged("CellIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameplayService.IGameplayService")]
    public interface IGameplayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        SnakeAndLaddersFinalProject.GameplayService.RollDiceResponseDto RollDice(SnakeAndLaddersFinalProject.GameplayService.RollDiceRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameplayService.RollDiceResponseDto> RollDiceAsync(SnakeAndLaddersFinalProject.GameplayService.RollDiceRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayServiceChannel : SnakeAndLaddersFinalProject.GameplayService.IGameplayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameplayServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.GameplayService.IGameplayService>, SnakeAndLaddersFinalProject.GameplayService.IGameplayService {
        
        public GameplayServiceClient() {
        }
        
        public GameplayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameplayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.GameplayService.RollDiceResponseDto RollDice(SnakeAndLaddersFinalProject.GameplayService.RollDiceRequestDto request) {
            return base.Channel.RollDice(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameplayService.RollDiceResponseDto> RollDiceAsync(SnakeAndLaddersFinalProject.GameplayService.RollDiceRequestDto request) {
            return base.Channel.RollDiceAsync(request);
        }
    }
}
