//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.GameBoardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBoardRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class CreateBoardRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.BoardSizeOption BoardSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableDiceCellsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableItemCellsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableMessageCellsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] PlayerUserIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.BoardSizeOption BoardSize {
            get {
                return this.BoardSizeField;
            }
            set {
                if ((this.BoardSizeField.Equals(value) != true)) {
                    this.BoardSizeField = value;
                    this.RaisePropertyChanged("BoardSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((object.ReferenceEquals(this.DifficultyField, value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableDiceCells {
            get {
                return this.EnableDiceCellsField;
            }
            set {
                if ((this.EnableDiceCellsField.Equals(value) != true)) {
                    this.EnableDiceCellsField = value;
                    this.RaisePropertyChanged("EnableDiceCells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableItemCells {
            get {
                return this.EnableItemCellsField;
            }
            set {
                if ((this.EnableItemCellsField.Equals(value) != true)) {
                    this.EnableItemCellsField = value;
                    this.RaisePropertyChanged("EnableItemCells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableMessageCells {
            get {
                return this.EnableMessageCellsField;
            }
            set {
                if ((this.EnableMessageCellsField.Equals(value) != true)) {
                    this.EnableMessageCellsField = value;
                    this.RaisePropertyChanged("EnableMessageCells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] PlayerUserIds {
            get {
                return this.PlayerUserIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUserIdsField, value) != true)) {
                    this.PlayerUserIdsField = value;
                    this.RaisePropertyChanged("PlayerUserIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardSizeOption", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Helpers")]
    public enum BoardSizeOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EightByEight = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TenByTen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwelveByTwelve = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBoardResponseDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class CreateBoardResponseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto BoardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardDefinitionDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class BoardDefinitionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.BoardSizeOption BoardSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.BoardCellDto[] CellsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.BoardLinkDto[] LinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.BoardSizeOption BoardSize {
            get {
                return this.BoardSizeField;
            }
            set {
                if ((this.BoardSizeField.Equals(value) != true)) {
                    this.BoardSizeField = value;
                    this.RaisePropertyChanged("BoardSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.BoardCellDto[] Cells {
            get {
                return this.CellsField;
            }
            set {
                if ((object.ReferenceEquals(this.CellsField, value) != true)) {
                    this.CellsField = value;
                    this.RaisePropertyChanged("Cells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((this.ColumnsField.Equals(value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.BoardLinkDto[] Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((this.RowsField.Equals(value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardCellDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class BoardCellDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.GameBoardService.SpecialCellType SpecialTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Column {
            get {
                return this.ColumnField;
            }
            set {
                if ((this.ColumnField.Equals(value) != true)) {
                    this.ColumnField = value;
                    this.RaisePropertyChanged("Column");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDark {
            get {
                return this.IsDarkField;
            }
            set {
                if ((this.IsDarkField.Equals(value) != true)) {
                    this.IsDarkField = value;
                    this.RaisePropertyChanged("IsDark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinal {
            get {
                return this.IsFinalField;
            }
            set {
                if ((this.IsFinalField.Equals(value) != true)) {
                    this.IsFinalField = value;
                    this.RaisePropertyChanged("IsFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStart {
            get {
                return this.IsStartField;
            }
            set {
                if ((this.IsStartField.Equals(value) != true)) {
                    this.IsStartField = value;
                    this.RaisePropertyChanged("IsStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.GameBoardService.SpecialCellType SpecialType {
            get {
                return this.SpecialTypeField;
            }
            set {
                if ((this.SpecialTypeField.Equals(value) != true)) {
                    this.SpecialTypeField = value;
                    this.RaisePropertyChanged("SpecialType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardLinkDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class BoardLinkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLadderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndIndex {
            get {
                return this.EndIndexField;
            }
            set {
                if ((this.EndIndexField.Equals(value) != true)) {
                    this.EndIndexField = value;
                    this.RaisePropertyChanged("EndIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLadder {
            get {
                return this.IsLadderField;
            }
            set {
                if ((this.IsLadderField.Equals(value) != true)) {
                    this.IsLadderField = value;
                    this.RaisePropertyChanged("IsLadder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartIndex {
            get {
                return this.StartIndexField;
            }
            set {
                if ((this.StartIndexField.Equals(value) != true)) {
                    this.StartIndexField = value;
                    this.RaisePropertyChanged("StartIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialCellType", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Helpers")]
    public enum SpecialCellType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dice = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Item = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameBoardService.IGameBoardService")]
    public interface IGameBoardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameBoardService/CreateBoard", ReplyAction="http://tempuri.org/IGameBoardService/CreateBoardResponse")]
        SnakeAndLaddersFinalProject.GameBoardService.CreateBoardResponseDto CreateBoard(SnakeAndLaddersFinalProject.GameBoardService.CreateBoardRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameBoardService/CreateBoard", ReplyAction="http://tempuri.org/IGameBoardService/CreateBoardResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameBoardService.CreateBoardResponseDto> CreateBoardAsync(SnakeAndLaddersFinalProject.GameBoardService.CreateBoardRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameBoardService/GetBoard", ReplyAction="http://tempuri.org/IGameBoardService/GetBoardResponse")]
        SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto GetBoard(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameBoardService/GetBoard", ReplyAction="http://tempuri.org/IGameBoardService/GetBoardResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto> GetBoardAsync(int gameId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameBoardServiceChannel : SnakeAndLaddersFinalProject.GameBoardService.IGameBoardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameBoardServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.GameBoardService.IGameBoardService>, SnakeAndLaddersFinalProject.GameBoardService.IGameBoardService {
        
        public GameBoardServiceClient() {
        }
        
        public GameBoardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameBoardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameBoardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameBoardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.GameBoardService.CreateBoardResponseDto CreateBoard(SnakeAndLaddersFinalProject.GameBoardService.CreateBoardRequestDto request) {
            return base.Channel.CreateBoard(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameBoardService.CreateBoardResponseDto> CreateBoardAsync(SnakeAndLaddersFinalProject.GameBoardService.CreateBoardRequestDto request) {
            return base.Channel.CreateBoardAsync(request);
        }
        
        public SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto GetBoard(int gameId) {
            return base.Channel.GetBoard(gameId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.GameBoardService.BoardDefinitionDto> GetBoardAsync(int gameId) {
            return base.Channel.GetBoardAsync(gameId);
        }
    }
}
