//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.InventoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventorySnapshotDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class InventorySnapshotDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.InventoryService.InventoryDiceDto[] DiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.InventoryService.InventoryItemDto[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.InventoryService.InventoryDiceDto[] Dice {
            get {
                return this.DiceField;
            }
            set {
                if ((object.ReferenceEquals(this.DiceField, value) != true)) {
                    this.DiceField = value;
                    this.RaisePropertyChanged("Dice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.InventoryService.InventoryItemDto[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryDiceDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class InventoryDiceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> SlotNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiceCode {
            get {
                return this.DiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiceCodeField, value) != true)) {
                    this.DiceCodeField = value;
                    this.RaisePropertyChanged("DiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceId {
            get {
                return this.DiceIdField;
            }
            set {
                if ((this.DiceIdField.Equals(value) != true)) {
                    this.DiceIdField = value;
                    this.RaisePropertyChanged("DiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlotNumber {
            get {
                return this.SlotNumberField;
            }
            set {
                if ((this.SlotNumberField.Equals(value) != true)) {
                    this.SlotNumberField = value;
                    this.RaisePropertyChanged("SlotNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryItemDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos.Gameplay")]
    [System.SerializableAttribute()]
    public partial class InventoryItemDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> SlotNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectCode {
            get {
                return this.ObjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectCodeField, value) != true)) {
                    this.ObjectCodeField = value;
                    this.RaisePropertyChanged("ObjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectId {
            get {
                return this.ObjectIdField;
            }
            set {
                if ((this.ObjectIdField.Equals(value) != true)) {
                    this.ObjectIdField = value;
                    this.RaisePropertyChanged("ObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SlotNumber {
            get {
                return this.SlotNumberField;
            }
            set {
                if ((this.SlotNumberField.Equals(value) != true)) {
                    this.SlotNumberField = value;
                    this.RaisePropertyChanged("SlotNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryService.IInventoryService")]
    public interface IInventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/GetInventory", ReplyAction="http://tempuri.org/IInventoryService/GetInventoryResponse")]
        SnakeAndLaddersFinalProject.InventoryService.InventorySnapshotDto GetInventory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/GetInventory", ReplyAction="http://tempuri.org/IInventoryService/GetInventoryResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.InventoryService.InventorySnapshotDto> GetInventoryAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UpdateSelectedItems", ReplyAction="http://tempuri.org/IInventoryService/UpdateSelectedItemsResponse")]
        void UpdateSelectedItems(int userId, System.Nullable<int> slot1ObjectId, System.Nullable<int> slot2ObjectId, System.Nullable<int> slot3ObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UpdateSelectedItems", ReplyAction="http://tempuri.org/IInventoryService/UpdateSelectedItemsResponse")]
        System.Threading.Tasks.Task UpdateSelectedItemsAsync(int userId, System.Nullable<int> slot1ObjectId, System.Nullable<int> slot2ObjectId, System.Nullable<int> slot3ObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UpdateSelectedDice", ReplyAction="http://tempuri.org/IInventoryService/UpdateSelectedDiceResponse")]
        void UpdateSelectedDice(int userId, System.Nullable<int> slot1DiceId, System.Nullable<int> slot2DiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UpdateSelectedDice", ReplyAction="http://tempuri.org/IInventoryService/UpdateSelectedDiceResponse")]
        System.Threading.Tasks.Task UpdateSelectedDiceAsync(int userId, System.Nullable<int> slot1DiceId, System.Nullable<int> slot2DiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/EquipItemToSlot", ReplyAction="http://tempuri.org/IInventoryService/EquipItemToSlotResponse")]
        void EquipItemToSlot(int userId, byte slotNumber, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/EquipItemToSlot", ReplyAction="http://tempuri.org/IInventoryService/EquipItemToSlotResponse")]
        System.Threading.Tasks.Task EquipItemToSlotAsync(int userId, byte slotNumber, int objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UnequipItemFromSlot", ReplyAction="http://tempuri.org/IInventoryService/UnequipItemFromSlotResponse")]
        void UnequipItemFromSlot(int userId, byte slotNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UnequipItemFromSlot", ReplyAction="http://tempuri.org/IInventoryService/UnequipItemFromSlotResponse")]
        System.Threading.Tasks.Task UnequipItemFromSlotAsync(int userId, byte slotNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/EquipDiceToSlot", ReplyAction="http://tempuri.org/IInventoryService/EquipDiceToSlotResponse")]
        void EquipDiceToSlot(int userId, byte slotNumber, int diceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/EquipDiceToSlot", ReplyAction="http://tempuri.org/IInventoryService/EquipDiceToSlotResponse")]
        System.Threading.Tasks.Task EquipDiceToSlotAsync(int userId, byte slotNumber, int diceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UnequipDiceFromSlot", ReplyAction="http://tempuri.org/IInventoryService/UnequipDiceFromSlotResponse")]
        void UnequipDiceFromSlot(int userId, byte slotNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventoryService/UnequipDiceFromSlot", ReplyAction="http://tempuri.org/IInventoryService/UnequipDiceFromSlotResponse")]
        System.Threading.Tasks.Task UnequipDiceFromSlotAsync(int userId, byte slotNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventoryServiceChannel : SnakeAndLaddersFinalProject.InventoryService.IInventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.InventoryService.IInventoryService>, SnakeAndLaddersFinalProject.InventoryService.IInventoryService {
        
        public InventoryServiceClient() {
        }
        
        public InventoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.InventoryService.InventorySnapshotDto GetInventory(int userId) {
            return base.Channel.GetInventory(userId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.InventoryService.InventorySnapshotDto> GetInventoryAsync(int userId) {
            return base.Channel.GetInventoryAsync(userId);
        }
        
        public void UpdateSelectedItems(int userId, System.Nullable<int> slot1ObjectId, System.Nullable<int> slot2ObjectId, System.Nullable<int> slot3ObjectId) {
            base.Channel.UpdateSelectedItems(userId, slot1ObjectId, slot2ObjectId, slot3ObjectId);
        }
        
        public System.Threading.Tasks.Task UpdateSelectedItemsAsync(int userId, System.Nullable<int> slot1ObjectId, System.Nullable<int> slot2ObjectId, System.Nullable<int> slot3ObjectId) {
            return base.Channel.UpdateSelectedItemsAsync(userId, slot1ObjectId, slot2ObjectId, slot3ObjectId);
        }
        
        public void UpdateSelectedDice(int userId, System.Nullable<int> slot1DiceId, System.Nullable<int> slot2DiceId) {
            base.Channel.UpdateSelectedDice(userId, slot1DiceId, slot2DiceId);
        }
        
        public System.Threading.Tasks.Task UpdateSelectedDiceAsync(int userId, System.Nullable<int> slot1DiceId, System.Nullable<int> slot2DiceId) {
            return base.Channel.UpdateSelectedDiceAsync(userId, slot1DiceId, slot2DiceId);
        }
        
        public void EquipItemToSlot(int userId, byte slotNumber, int objectId) {
            base.Channel.EquipItemToSlot(userId, slotNumber, objectId);
        }
        
        public System.Threading.Tasks.Task EquipItemToSlotAsync(int userId, byte slotNumber, int objectId) {
            return base.Channel.EquipItemToSlotAsync(userId, slotNumber, objectId);
        }
        
        public void UnequipItemFromSlot(int userId, byte slotNumber) {
            base.Channel.UnequipItemFromSlot(userId, slotNumber);
        }
        
        public System.Threading.Tasks.Task UnequipItemFromSlotAsync(int userId, byte slotNumber) {
            return base.Channel.UnequipItemFromSlotAsync(userId, slotNumber);
        }
        
        public void EquipDiceToSlot(int userId, byte slotNumber, int diceId) {
            base.Channel.EquipDiceToSlot(userId, slotNumber, diceId);
        }
        
        public System.Threading.Tasks.Task EquipDiceToSlotAsync(int userId, byte slotNumber, int diceId) {
            return base.Channel.EquipDiceToSlotAsync(userId, slotNumber, diceId);
        }
        
        public void UnequipDiceFromSlot(int userId, byte slotNumber) {
            base.Channel.UnequipDiceFromSlot(userId, slotNumber);
        }
        
        public System.Threading.Tasks.Task UnequipDiceFromSlotAsync(int userId, byte slotNumber) {
            return base.Channel.UnequipDiceFromSlotAsync(userId, slotNumber);
        }
    }
}
