//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.FriendsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendLinkDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class FriendLinkDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendLinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.FriendsService.FriendRequestStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserId1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserId2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendLinkId {
            get {
                return this.FriendLinkIdField;
            }
            set {
                if ((this.FriendLinkIdField.Equals(value) != true)) {
                    this.FriendLinkIdField = value;
                    this.RaisePropertyChanged("FriendLinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.FriendsService.FriendRequestStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId1 {
            get {
                return this.UserId1Field;
            }
            set {
                if ((this.UserId1Field.Equals(value) != true)) {
                    this.UserId1Field = value;
                    this.RaisePropertyChanged("UserId1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId2 {
            get {
                return this.UserId2Field;
            }
            set {
                if ((this.UserId2Field.Equals(value) != true)) {
                    this.UserId2Field = value;
                    this.RaisePropertyChanged("UserId2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestStatus", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Enums")]
    public enum FriendRequestStatus : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accepted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendListItemDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class FriendListItemDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendLinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePhotoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendLinkId {
            get {
                return this.FriendLinkIdField;
            }
            set {
                if ((this.FriendLinkIdField.Equals(value) != true)) {
                    this.FriendLinkIdField = value;
                    this.RaisePropertyChanged("FriendLinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendUserId {
            get {
                return this.FriendUserIdField;
            }
            set {
                if ((this.FriendUserIdField.Equals(value) != true)) {
                    this.FriendUserIdField = value;
                    this.RaisePropertyChanged("FriendUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendUserName {
            get {
                return this.FriendUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendUserNameField, value) != true)) {
                    this.FriendUserNameField = value;
                    this.RaisePropertyChanged("FriendUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePhotoId {
            get {
                return this.ProfilePhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePhotoIdField, value) != true)) {
                    this.ProfilePhotoIdField = value;
                    this.RaisePropertyChanged("ProfilePhotoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestItemDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class FriendRequestItemDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendLinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequesterUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.FriendsService.FriendRequestStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetUserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendLinkId {
            get {
                return this.FriendLinkIdField;
            }
            set {
                if ((this.FriendLinkIdField.Equals(value) != true)) {
                    this.FriendLinkIdField = value;
                    this.RaisePropertyChanged("FriendLinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequesterUserId {
            get {
                return this.RequesterUserIdField;
            }
            set {
                if ((this.RequesterUserIdField.Equals(value) != true)) {
                    this.RequesterUserIdField = value;
                    this.RaisePropertyChanged("RequesterUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequesterUserName {
            get {
                return this.RequesterUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterUserNameField, value) != true)) {
                    this.RequesterUserNameField = value;
                    this.RaisePropertyChanged("RequesterUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.FriendsService.FriendRequestStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetUserId {
            get {
                return this.TargetUserIdField;
            }
            set {
                if ((this.TargetUserIdField.Equals(value) != true)) {
                    this.TargetUserIdField = value;
                    this.RaisePropertyChanged("TargetUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUserName {
            get {
                return this.TargetUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetUserNameField, value) != true)) {
                    this.TargetUserNameField = value;
                    this.RaisePropertyChanged("TargetUserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBriefDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class UserBriefDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePhotoId {
            get {
                return this.ProfilePhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePhotoIdField, value) != true)) {
                    this.ProfilePhotoIdField = value;
                    this.RaisePropertyChanged("ProfilePhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendsService.IFriendsService")]
    public interface IFriendsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/SendFriendRequestResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto SendFriendRequest(string token, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto> SendFriendRequestAsync(string token, int targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/AcceptFriendRequestResponse")]
        void AcceptFriendRequest(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/AcceptFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task AcceptFriendRequestAsync(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/RejectFriendRequestResponse")]
        void RejectFriendRequest(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/RejectFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/RejectFriendRequestResponse")]
        System.Threading.Tasks.Task RejectFriendRequestAsync(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/CancelFriendRequestResponse")]
        void CancelFriendRequest(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/CancelFriendRequest", ReplyAction="http://tempuri.org/IFriendsService/CancelFriendRequestResponse")]
        System.Threading.Tasks.Task CancelFriendRequestAsync(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendsService/RemoveFriendResponse")]
        void RemoveFriend(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendsService/RemoveFriendResponse")]
        System.Threading.Tasks.Task RemoveFriendAsync(string token, int friendLinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetStatus", ReplyAction="http://tempuri.org/IFriendsService/GetStatusResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto GetStatus(string token, int otherUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetStatus", ReplyAction="http://tempuri.org/IFriendsService/GetStatusResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto> GetStatusAsync(string token, int otherUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetFriendsIds", ReplyAction="http://tempuri.org/IFriendsService/GetFriendsIdsResponse")]
        int[] GetFriendsIds(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetFriendsIds", ReplyAction="http://tempuri.org/IFriendsService/GetFriendsIdsResponse")]
        System.Threading.Tasks.Task<int[]> GetFriendsIdsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetIncomingPending", ReplyAction="http://tempuri.org/IFriendsService/GetIncomingPendingResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[] GetIncomingPending(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetIncomingPending", ReplyAction="http://tempuri.org/IFriendsService/GetIncomingPendingResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[]> GetIncomingPendingAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetOutgoingPending", ReplyAction="http://tempuri.org/IFriendsService/GetOutgoingPendingResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[] GetOutgoingPending(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetOutgoingPending", ReplyAction="http://tempuri.org/IFriendsService/GetOutgoingPendingResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[]> GetOutgoingPendingAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetFriends", ReplyAction="http://tempuri.org/IFriendsService/GetFriendsResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendListItemDto[] GetFriends(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetFriends", ReplyAction="http://tempuri.org/IFriendsService/GetFriendsResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendListItemDto[]> GetFriendsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetIncomingRequests", ReplyAction="http://tempuri.org/IFriendsService/GetIncomingRequestsResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[] GetIncomingRequests(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetIncomingRequests", ReplyAction="http://tempuri.org/IFriendsService/GetIncomingRequestsResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[]> GetIncomingRequestsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetOutgoingRequests", ReplyAction="http://tempuri.org/IFriendsService/GetOutgoingRequestsResponse")]
        SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[] GetOutgoingRequests(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/GetOutgoingRequests", ReplyAction="http://tempuri.org/IFriendsService/GetOutgoingRequestsResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[]> GetOutgoingRequestsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/SearchUsers", ReplyAction="http://tempuri.org/IFriendsService/SearchUsersResponse")]
        SnakeAndLaddersFinalProject.FriendsService.UserBriefDto[] SearchUsers(string token, string query, int maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendsService/SearchUsers", ReplyAction="http://tempuri.org/IFriendsService/SearchUsersResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.UserBriefDto[]> SearchUsersAsync(string token, string query, int maxResults);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendsServiceChannel : SnakeAndLaddersFinalProject.FriendsService.IFriendsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendsServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.FriendsService.IFriendsService>, SnakeAndLaddersFinalProject.FriendsService.IFriendsService {
        
        public FriendsServiceClient() {
        }
        
        public FriendsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto SendFriendRequest(string token, int targetUserId) {
            return base.Channel.SendFriendRequest(token, targetUserId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto> SendFriendRequestAsync(string token, int targetUserId) {
            return base.Channel.SendFriendRequestAsync(token, targetUserId);
        }
        
        public void AcceptFriendRequest(string token, int friendLinkId) {
            base.Channel.AcceptFriendRequest(token, friendLinkId);
        }
        
        public System.Threading.Tasks.Task AcceptFriendRequestAsync(string token, int friendLinkId) {
            return base.Channel.AcceptFriendRequestAsync(token, friendLinkId);
        }
        
        public void RejectFriendRequest(string token, int friendLinkId) {
            base.Channel.RejectFriendRequest(token, friendLinkId);
        }
        
        public System.Threading.Tasks.Task RejectFriendRequestAsync(string token, int friendLinkId) {
            return base.Channel.RejectFriendRequestAsync(token, friendLinkId);
        }
        
        public void CancelFriendRequest(string token, int friendLinkId) {
            base.Channel.CancelFriendRequest(token, friendLinkId);
        }
        
        public System.Threading.Tasks.Task CancelFriendRequestAsync(string token, int friendLinkId) {
            return base.Channel.CancelFriendRequestAsync(token, friendLinkId);
        }
        
        public void RemoveFriend(string token, int friendLinkId) {
            base.Channel.RemoveFriend(token, friendLinkId);
        }
        
        public System.Threading.Tasks.Task RemoveFriendAsync(string token, int friendLinkId) {
            return base.Channel.RemoveFriendAsync(token, friendLinkId);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto GetStatus(string token, int otherUserId) {
            return base.Channel.GetStatus(token, otherUserId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto> GetStatusAsync(string token, int otherUserId) {
            return base.Channel.GetStatusAsync(token, otherUserId);
        }
        
        public int[] GetFriendsIds(string token) {
            return base.Channel.GetFriendsIds(token);
        }
        
        public System.Threading.Tasks.Task<int[]> GetFriendsIdsAsync(string token) {
            return base.Channel.GetFriendsIdsAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[] GetIncomingPending(string token) {
            return base.Channel.GetIncomingPending(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[]> GetIncomingPendingAsync(string token) {
            return base.Channel.GetIncomingPendingAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[] GetOutgoingPending(string token) {
            return base.Channel.GetOutgoingPending(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendLinkDto[]> GetOutgoingPendingAsync(string token) {
            return base.Channel.GetOutgoingPendingAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendListItemDto[] GetFriends(string token) {
            return base.Channel.GetFriends(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendListItemDto[]> GetFriendsAsync(string token) {
            return base.Channel.GetFriendsAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[] GetIncomingRequests(string token) {
            return base.Channel.GetIncomingRequests(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[]> GetIncomingRequestsAsync(string token) {
            return base.Channel.GetIncomingRequestsAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[] GetOutgoingRequests(string token) {
            return base.Channel.GetOutgoingRequests(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.FriendRequestItemDto[]> GetOutgoingRequestsAsync(string token) {
            return base.Channel.GetOutgoingRequestsAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.FriendsService.UserBriefDto[] SearchUsers(string token, string query, int maxResults) {
            return base.Channel.SearchUsers(token, query, maxResults);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.FriendsService.UserBriefDto[]> SearchUsersAsync(string token, string query, int maxResults) {
            return base.Channel.SearchUsersAsync(token, query, maxResults);
        }
    }
}
