//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.ShopService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopChestRarity", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Enums")]
    public enum ShopChestRarity : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Common = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Epic = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Legendary = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopRewardDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class ShopRewardDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoinsAfterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoinsBeforeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewForUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RewardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RewardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RewardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SnakeAndLaddersFinalProject.ShopService.ShopRewardType RewardTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoinsAfter {
            get {
                return this.CoinsAfterField;
            }
            set {
                if ((this.CoinsAfterField.Equals(value) != true)) {
                    this.CoinsAfterField = value;
                    this.RaisePropertyChanged("CoinsAfter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoinsBefore {
            get {
                return this.CoinsBeforeField;
            }
            set {
                if ((this.CoinsBeforeField.Equals(value) != true)) {
                    this.CoinsBeforeField = value;
                    this.RaisePropertyChanged("CoinsBefore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNewForUser {
            get {
                return this.IsNewForUserField;
            }
            set {
                if ((this.IsNewForUserField.Equals(value) != true)) {
                    this.IsNewForUserField = value;
                    this.RaisePropertyChanged("IsNewForUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RewardCode {
            get {
                return this.RewardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RewardCodeField, value) != true)) {
                    this.RewardCodeField = value;
                    this.RaisePropertyChanged("RewardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RewardId {
            get {
                return this.RewardIdField;
            }
            set {
                if ((this.RewardIdField.Equals(value) != true)) {
                    this.RewardIdField = value;
                    this.RaisePropertyChanged("RewardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RewardName {
            get {
                return this.RewardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RewardNameField, value) != true)) {
                    this.RewardNameField = value;
                    this.RaisePropertyChanged("RewardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakeAndLaddersFinalProject.ShopService.ShopRewardType RewardType {
            get {
                return this.RewardTypeField;
            }
            set {
                if ((this.RewardTypeField.Equals(value) != true)) {
                    this.RewardTypeField = value;
                    this.RaisePropertyChanged("RewardType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopRewardType", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Enums")]
    public enum ShopRewardType : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dice = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StickerPack = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Item = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StickerDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class StickerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StickerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StickerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StickerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StickerCode {
            get {
                return this.StickerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StickerCodeField, value) != true)) {
                    this.StickerCodeField = value;
                    this.RaisePropertyChanged("StickerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StickerId {
            get {
                return this.StickerIdField;
            }
            set {
                if ((this.StickerIdField.Equals(value) != true)) {
                    this.StickerIdField = value;
                    this.RaisePropertyChanged("StickerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StickerName {
            get {
                return this.StickerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StickerNameField, value) != true)) {
                    this.StickerNameField = value;
                    this.RaisePropertyChanged("StickerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShopService.IShopService")]
    public interface IShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseAvatarChest", ReplyAction="http://tempuri.org/IShopService/PurchaseAvatarChestResponse")]
        SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseAvatarChest(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseAvatarChest", ReplyAction="http://tempuri.org/IShopService/PurchaseAvatarChestResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseAvatarChestAsync(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseStickerChest", ReplyAction="http://tempuri.org/IShopService/PurchaseStickerChestResponse")]
        SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseStickerChest(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseStickerChest", ReplyAction="http://tempuri.org/IShopService/PurchaseStickerChestResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseStickerChestAsync(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseDice", ReplyAction="http://tempuri.org/IShopService/PurchaseDiceResponse")]
        SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseDice(string token, int diceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseDice", ReplyAction="http://tempuri.org/IShopService/PurchaseDiceResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseDiceAsync(string token, int diceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseItemChest", ReplyAction="http://tempuri.org/IShopService/PurchaseItemChestResponse")]
        SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseItemChest(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseItemChest", ReplyAction="http://tempuri.org/IShopService/PurchaseItemChestResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseItemChestAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/GetCurrentCoins", ReplyAction="http://tempuri.org/IShopService/GetCurrentCoinsResponse")]
        int GetCurrentCoins(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/GetCurrentCoins", ReplyAction="http://tempuri.org/IShopService/GetCurrentCoinsResponse")]
        System.Threading.Tasks.Task<int> GetCurrentCoinsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/GetUserStickers", ReplyAction="http://tempuri.org/IShopService/GetUserStickersResponse")]
        SnakeAndLaddersFinalProject.ShopService.StickerDto[] GetUserStickers(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/GetUserStickers", ReplyAction="http://tempuri.org/IShopService/GetUserStickersResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.StickerDto[]> GetUserStickersAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServiceChannel : SnakeAndLaddersFinalProject.ShopService.IShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.ShopService.IShopService>, SnakeAndLaddersFinalProject.ShopService.IShopService {
        
        public ShopServiceClient() {
        }
        
        public ShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseAvatarChest(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity) {
            return base.Channel.PurchaseAvatarChest(token, rarity);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseAvatarChestAsync(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity) {
            return base.Channel.PurchaseAvatarChestAsync(token, rarity);
        }
        
        public SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseStickerChest(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity) {
            return base.Channel.PurchaseStickerChest(token, rarity);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseStickerChestAsync(string token, SnakeAndLaddersFinalProject.ShopService.ShopChestRarity rarity) {
            return base.Channel.PurchaseStickerChestAsync(token, rarity);
        }
        
        public SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseDice(string token, int diceId) {
            return base.Channel.PurchaseDice(token, diceId);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseDiceAsync(string token, int diceId) {
            return base.Channel.PurchaseDiceAsync(token, diceId);
        }
        
        public SnakeAndLaddersFinalProject.ShopService.ShopRewardDto PurchaseItemChest(string token) {
            return base.Channel.PurchaseItemChest(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.ShopRewardDto> PurchaseItemChestAsync(string token) {
            return base.Channel.PurchaseItemChestAsync(token);
        }
        
        public int GetCurrentCoins(string token) {
            return base.Channel.GetCurrentCoins(token);
        }
        
        public System.Threading.Tasks.Task<int> GetCurrentCoinsAsync(string token) {
            return base.Channel.GetCurrentCoinsAsync(token);
        }
        
        public SnakeAndLaddersFinalProject.ShopService.StickerDto[] GetUserStickers(string token) {
            return base.Channel.GetUserStickers(token);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.ShopService.StickerDto[]> GetUserStickersAsync(string token) {
            return base.Channel.GetUserStickersAsync(token);
        }
    }
}
