//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.MatchInvitationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InviteFriendToGameRequestDto", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class InviteFriendToGameRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FriendUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FriendUserId {
            get {
                return this.FriendUserIdField;
            }
            set {
                if ((this.FriendUserIdField.Equals(value) != true)) {
                    this.FriendUserIdField = value;
                    this.RaisePropertyChanged("FriendUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameCode {
            get {
                return this.GameCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameCodeField, value) != true)) {
                    this.GameCodeField = value;
                    this.RaisePropertyChanged("GameCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/SnakeAndLadders.Contracts.Dtos")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchInvitationService.IMatchInvitationService")]
    public interface IMatchInvitationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchInvitationService/InviteFriendToGame", ReplyAction="http://tempuri.org/IMatchInvitationService/InviteFriendToGameResponse")]
        SnakeAndLaddersFinalProject.MatchInvitationService.OperationResult InviteFriendToGame(SnakeAndLaddersFinalProject.MatchInvitationService.InviteFriendToGameRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchInvitationService/InviteFriendToGame", ReplyAction="http://tempuri.org/IMatchInvitationService/InviteFriendToGameResponse")]
        System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.MatchInvitationService.OperationResult> InviteFriendToGameAsync(SnakeAndLaddersFinalProject.MatchInvitationService.InviteFriendToGameRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchInvitationServiceChannel : SnakeAndLaddersFinalProject.MatchInvitationService.IMatchInvitationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchInvitationServiceClient : System.ServiceModel.ClientBase<SnakeAndLaddersFinalProject.MatchInvitationService.IMatchInvitationService>, SnakeAndLaddersFinalProject.MatchInvitationService.IMatchInvitationService {
        
        public MatchInvitationServiceClient() {
        }
        
        public MatchInvitationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchInvitationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchInvitationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchInvitationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SnakeAndLaddersFinalProject.MatchInvitationService.OperationResult InviteFriendToGame(SnakeAndLaddersFinalProject.MatchInvitationService.InviteFriendToGameRequestDto request) {
            return base.Channel.InviteFriendToGame(request);
        }
        
        public System.Threading.Tasks.Task<SnakeAndLaddersFinalProject.MatchInvitationService.OperationResult> InviteFriendToGameAsync(SnakeAndLaddersFinalProject.MatchInvitationService.InviteFriendToGameRequestDto request) {
            return base.Channel.InviteFriendToGameAsync(request);
        }
    }
}
