//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnakeAndLaddersFinalProject.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait {0} seconds before trying again..
        /// </summary>
        public static string Auth_ThrottleWaitFmt {
            get {
                return ResourceManager.GetString("Auth_ThrottleWaitFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account has been deleted..
        /// </summary>
        public static string AuthAccountDeleted {
            get {
                return ResourceManager.GetString("AuthAccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is currently banned..
        /// </summary>
        public static string AuthBannedGeneric {
            get {
                return ResourceManager.GetString("AuthBannedGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account has been permanently banned..
        /// </summary>
        public static string AuthBannedPermanent {
            get {
                return ResourceManager.GetString("AuthBannedPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is banned until {0}..
        /// </summary>
        public static string AuthBannedUntilFmt {
            get {
                return ResourceManager.GetString("AuthBannedUntilFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code has expired. Please request a new one..
        /// </summary>
        public static string AuthCodeExpired {
            get {
                return ResourceManager.GetString("AuthCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code is not valid..
        /// </summary>
        public static string AuthCodeInvalid {
            get {
                return ResourceManager.GetString("AuthCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must request a verification code before continuing.
        /// </summary>
        public static string AuthCodeNotRequested {
            get {
                return ResourceManager.GetString("AuthCodeNotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email address is already registered..
        /// </summary>
        public static string AuthEmailAlreadyExists {
            get {
                return ResourceManager.GetString("AuthEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required..
        /// </summary>
        public static string AuthEmailRequired {
            get {
                return ResourceManager.GetString("AuthEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We could not send the email. Please try again later..
        /// </summary>
        public static string AuthEmailSendFailed {
            get {
                return ResourceManager.GetString("AuthEmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid credentials, please verify them.
        /// </summary>
        public static string AuthInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A server error occurred while processing your request..
        /// </summary>
        public static string AuthServerError {
            get {
                return ResourceManager.GetString("AuthServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait {0} seconds before requesting a new code..
        /// </summary>
        public static string AuthThrottleWaitFmt {
            get {
                return ResourceManager.GetString("AuthThrottleWaitFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is already taken..
        /// </summary>
        public static string AuthUserNameAlreadyExists {
            get {
                return ResourceManager.GetString("AuthUserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string bntContinueText {
            get {
                return ResourceManager.GetString("bntContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        public static string bntInviteFriendText {
            get {
                return ResourceManager.GetString("bntInviteFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string btnAcceptText {
            get {
                return ResourceManager.GetString("btnAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string btnAddFriendText {
            get {
                return ResourceManager.GetString("btnAddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string btnBackText {
            get {
                return ResourceManager.GetString("btnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a buy.
        /// </summary>
        public static string btnBuy {
            get {
                return ResourceManager.GetString("btnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change avatar.
        /// </summary>
        public static string btnChangeAvatarText {
            get {
                return ResourceManager.GetString("btnChangeAvatarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string btnChangePasswordText {
            get {
                return ResourceManager.GetString("btnChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Match.
        /// </summary>
        public static string btnCreateMatchText {
            get {
                return ResourceManager.GetString("btnCreateMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a leave match.
        /// </summary>
        public static string btnExitMatchText {
            get {
                return ResourceManager.GetString("btnExitMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exploiting.
        /// </summary>
        public static string btnExploitingText {
            get {
                return ResourceManager.GetString("btnExploitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a i forgot my password.
        /// </summary>
        public static string btnForgottenPasswordText {
            get {
                return ResourceManager.GetString("btnForgottenPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests.
        /// </summary>
        public static string btnFriendRequestsText {
            get {
                return ResourceManager.GetString("btnFriendRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btnFriendsText {
            get {
                return ResourceManager.GetString("btnFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Harassment.
        /// </summary>
        public static string btnHarassmentText {
            get {
                return ResourceManager.GetString("btnHarassmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inappropriate language.
        /// </summary>
        public static string btnInappropiateLangText {
            get {
                return ResourceManager.GetString("btnInappropiateLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        public static string btnInventoryText {
            get {
                return ResourceManager.GetString("btnInventoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string btnInviteFriendsText {
            get {
                return ResourceManager.GetString("btnInviteFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string btnJoinMatchText {
            get {
                return ResourceManager.GetString("btnJoinMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string btnLoginText {
            get {
                return ResourceManager.GetString("btnLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main window.
        /// </summary>
        public static string btnMainWindowText {
            get {
                return ResourceManager.GetString("btnMainWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other....
        /// </summary>
        public static string btnOtherReasonText {
            get {
                return ResourceManager.GetString("btnOtherReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a play as guest.
        /// </summary>
        public static string btnPlayAsGuestText {
            get {
                return ResourceManager.GetString("btnPlayAsGuestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string btnProfileEditText {
            get {
                return ResourceManager.GetString("btnProfileEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnProfileSaveText {
            get {
                return ResourceManager.GetString("btnProfileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string btnProfileText {
            get {
                return ResourceManager.GetString("btnProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        public static string btnRankingText {
            get {
                return ResourceManager.GetString("btnRankingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reject.
        /// </summary>
        public static string btnRejectText {
            get {
                return ResourceManager.GetString("btnRejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report player.
        /// </summary>
        public static string btnReportPlayerText {
            get {
                return ResourceManager.GetString("btnReportPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend the code.
        /// </summary>
        public static string btnResendCodeText {
            get {
                return ResourceManager.GetString("btnResendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send code.
        /// </summary>
        public static string btnSendCodeText {
            get {
                return ResourceManager.GetString("btnSendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btnSendText {
            get {
                return ResourceManager.GetString("btnSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string btnSettingsText {
            get {
                return ResourceManager.GetString("btnSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shop.
        /// </summary>
        public static string btnShopText {
            get {
                return ResourceManager.GetString("btnShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string btnSignUpText {
            get {
                return ResourceManager.GetString("btnSignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skins.
        /// </summary>
        public static string btnSkinsText {
            get {
                return ResourceManager.GetString("btnSkinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a start match.
        /// </summary>
        public static string btnStartMatchText {
            get {
                return ResourceManager.GetString("btnStartMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toxic behavior.
        /// </summary>
        public static string btnToxicBehaviorText {
            get {
                return ResourceManager.GetString("btnToxicBehaviorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unfriend.
        /// </summary>
        public static string btnUnfriendText {
            get {
                return ResourceManager.GetString("btnUnfriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This character cries when she has an exam.
        /// </summary>
        public static string character1DescriptionText {
            get {
                return ResourceManager.GetString("character1DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string chatTittle {
            get {
                return ResourceManager.GetString("chatTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins.
        /// </summary>
        public static string colRankingCoinsHeader {
            get {
                return ResourceManager.GetString("colRankingCoinsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        public static string colRankingPositionHeader {
            get {
                return ResourceManager.GetString("colRankingPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string colRankingUsernameHeader {
            get {
                return ResourceManager.GetString("colRankingUsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error accepting the request.
        /// </summary>
        public static string errorAcceptingRequestText {
            get {
                return ResourceManager.GetString("errorAcceptingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error canceling the request.
        /// </summary>
        public static string errorCancelingRequestText {
            get {
                return ResourceManager.GetString("errorCancelingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load friend list.
        /// </summary>
        public static string errorLoadingFriendsListText {
            get {
                return ResourceManager.GetString("errorLoadingFriendsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not load requests.
        /// </summary>
        public static string errorLoadingRequestsText {
            get {
                return ResourceManager.GetString("errorLoadingRequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error rejecting the request.
        /// </summary>
        public static string errorRejectingRequestText {
            get {
                return ResourceManager.GetString("errorRejectingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not remove friend.
        /// </summary>
        public static string errorRemovingFriendText {
            get {
                return ResourceManager.GetString("errorRemovingFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error searching for users.
        /// </summary>
        public static string errorSearchingUsersText {
            get {
                return ResourceManager.GetString("errorSearchingUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not sent the request.
        /// </summary>
        public static string errorSendingRequestText {
            get {
                return ResourceManager.GetString("errorSendingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request accepted.
        /// </summary>
        public static string friendAcceptedText {
            get {
                return ResourceManager.GetString("friendAcceptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request rejected.
        /// </summary>
        public static string friendRejectedText {
            get {
                return ResourceManager.GetString("friendRejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend successfully removed.
        /// </summary>
        public static string friendRemovedOkText {
            get {
                return ResourceManager.GetString("friendRemovedOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request canceled.
        /// </summary>
        public static string friendRequestCanceledText {
            get {
                return ResourceManager.GetString("friendRequestCanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent.
        /// </summary>
        public static string friendRequestSentText {
            get {
                return ResourceManager.GetString("friendRequestSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string infoTitle {
            get {
                return ResourceManager.GetString("infoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 500 coins.
        /// </summary>
        public static string ItemChestPrice {
            get {
                return ResourceManager.GetString("ItemChestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friends.
        /// </summary>
        public static string lblAddFriends {
            get {
                return ResourceManager.GetString("lblAddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 200 coins.
        /// </summary>
        public static string lblAvatarCommonPrice {
            get {
                return ResourceManager.GetString("lblAvatarCommonPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 400 coins.
        /// </summary>
        public static string lblAvatarEpicPrice {
            get {
                return ResourceManager.GetString("lblAvatarEpicPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 800 coins.
        /// </summary>
        public static string lblAvatarLegendaryPrice {
            get {
                return ResourceManager.GetString("lblAvatarLegendaryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legendary skin chest.
        /// </summary>
        public static string lblAvatarLegendaryTitle {
            get {
                return ResourceManager.GetString("lblAvatarLegendaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skins.
        /// </summary>
        public static string lblAvatarSectionTitle {
            get {
                return ResourceManager.GetString("lblAvatarSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Board size .
        /// </summary>
        public static string lblBoardSizeText {
            get {
                return ResourceManager.GetString("lblBoardSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string lblChangePasswordCodeText {
            get {
                return ResourceManager.GetString("lblChangePasswordCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string lblChangePasswordConfirmPasswordText {
            get {
                return ResourceManager.GetString("lblChangePasswordConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password.
        /// </summary>
        public static string lblChangePasswordCurrentPasswordText {
            get {
                return ResourceManager.GetString("lblChangePasswordCurrentPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your new password must meet the security requirements.
        /// </summary>
        public static string lblChangePasswordFooterText {
            get {
                return ResourceManager.GetString("lblChangePasswordFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your current password and choose a new one.
        /// </summary>
        public static string lblChangePasswordInstructionText {
            get {
                return ResourceManager.GetString("lblChangePasswordInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string lblChangePasswordNewPasswordText {
            get {
                return ResourceManager.GetString("lblChangePasswordNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string lblChangePasswordTitleText {
            get {
                return ResourceManager.GetString("lblChangePasswordTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character description.
        /// </summary>
        public static string lblcharacterDescriptionText {
            get {
                return ResourceManager.GetString("lblcharacterDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a coins.
        /// </summary>
        public static string lblCoinsQuantity {
            get {
                return ResourceManager.GetString("lblCoinsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins.
        /// </summary>
        public static string lblCoinsText {
            get {
                return ResourceManager.GetString("lblCoinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Coins.
        /// </summary>
        public static string lblCurrentCoins {
            get {
                return ResourceManager.GetString("lblCurrentCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 300 coins.
        /// </summary>
        public static string lblDice123Price {
            get {
                return ResourceManager.GetString("lblDice123Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1–3 dice.
        /// </summary>
        public static string lblDice123Title {
            get {
                return ResourceManager.GetString("lblDice123Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 300 coins.
        /// </summary>
        public static string lblDice456Price {
            get {
                return ResourceManager.GetString("lblDice456Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4–6 dice.
        /// </summary>
        public static string lblDice456Title {
            get {
                return ResourceManager.GetString("lblDice456Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 300 coins.
        /// </summary>
        public static string lblDiceNegativePrice {
            get {
                return ResourceManager.GetString("lblDiceNegativePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative dice.
        /// </summary>
        public static string lblDiceNegativeTitle {
            get {
                return ResourceManager.GetString("lblDiceNegativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dice.
        /// </summary>
        public static string lblDiceSectionTitle {
            get {
                return ResourceManager.GetString("lblDiceSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty.
        /// </summary>
        public static string lblDifficultyText {
            get {
                return ResourceManager.GetString("lblDifficultyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email verification.
        /// </summary>
        public static string lblEmailVerificationTitle {
            get {
                return ResourceManager.GetString("lblEmailVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find friends.
        /// </summary>
        public static string lblFindFriensText {
            get {
                return ResourceManager.GetString("lblFindFriensText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find match.
        /// </summary>
        public static string lblFindMatchText {
            get {
                return ResourceManager.GetString("lblFindMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests.
        /// </summary>
        public static string lblFriendRequestsTitle {
            get {
                return ResourceManager.GetString("lblFriendRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends List.
        /// </summary>
        public static string lblFriendsListTitle {
            get {
                return ResourceManager.GetString("lblFriendsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests received.
        /// </summary>
        public static string lblIncomingRequests {
            get {
                return ResourceManager.GetString("lblIncomingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventory.
        /// </summary>
        public static string lblInventory {
            get {
                return ResourceManager.GetString("lblInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item chest.
        /// </summary>
        public static string lblItemChestTitle {
            get {
                return ResourceManager.GetString("lblItemChestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a items.
        /// </summary>
        public static string lblItems {
            get {
                return ResourceManager.GetString("lblItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items.
        /// </summary>
        public static string lblItemSectionTitle {
            get {
                return ResourceManager.GetString("lblItemSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string lblLobby {
            get {
                return ResourceManager.GetString("lblLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches Lost.
        /// </summary>
        public static string lblMatchesLost {
            get {
                return ResourceManager.GetString("lblMatchesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches Played.
        /// </summary>
        public static string lblMatchesPlayed {
            get {
                return ResourceManager.GetString("lblMatchesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches Won.
        /// </summary>
        public static string lblMatchesWon {
            get {
                return ResourceManager.GetString("lblMatchesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match List.
        /// </summary>
        public static string lblMatchListTitle {
            get {
                return ResourceManager.GetString("lblMatchListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match settings.
        /// </summary>
        public static string lblMatchSettingsText {
            get {
                return ResourceManager.GetString("lblMatchSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highest Coin Count Achieved.
        /// </summary>
        public static string lblMaxCoinsEver {
            get {
                return ResourceManager.GetString("lblMaxCoinsEver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a music.
        /// </summary>
        public static string lblMusic {
            get {
                return ResourceManager.GetString("lblMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests sent.
        /// </summary>
        public static string lblOutgoingRequests {
            get {
                return ResourceManager.GetString("lblOutgoingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string lblPlayersText {
            get {
                return ResourceManager.GetString("lblPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string lblProfileDescriptionText {
            get {
                return ResourceManager.GetString("lblProfileDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile edit mode.
        /// </summary>
        public static string lblProfileEditModeText {
            get {
                return ResourceManager.GetString("lblProfileEditModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name.
        /// </summary>
        public static string lblProfileFirstNameText {
            get {
                return ResourceManager.GetString("lblProfileFirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string lblProfileLastNameText {
            get {
                return ResourceManager.GetString("lblProfileLastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics Profile.
        /// </summary>
        public static string lblProfileStatsTitle {
            get {
                return ResourceManager.GetString("lblProfileStatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My profile.
        /// </summary>
        public static string lblProfileTitle {
            get {
                return ResourceManager.GetString("lblProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string lblProfileUserNameCaptionText {
            get {
                return ResourceManager.GetString("lblProfileUserNameCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players are sorted by their coin count.
        /// </summary>
        public static string lblRankingFooterText {
            get {
                return ResourceManager.GetString("lblRankingFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players ranking.
        /// </summary>
        public static string lblRankingTitleText {
            get {
                return ResourceManager.GetString("lblRankingTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top-50 Ranking Position.
        /// </summary>
        public static string lblRankingTop50Position {
            get {
                return ResourceManager.GetString("lblRankingTop50Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new account.
        /// </summary>
        public static string lblRegisterTitle {
            get {
                return ResourceManager.GetString("lblRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report detail.
        /// </summary>
        public static string lblReportDetailText {
            get {
                return ResourceManager.GetString("lblReportDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your avatar.
        /// </summary>
        public static string lblSelectAvatarTitleText {
            get {
                return ResourceManager.GetString("lblSelectAvatarTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Common skin chest.
        /// </summary>
        public static string lblShopAvatarCommonTitle {
            get {
                return ResourceManager.GetString("lblShopAvatarCommonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epic skin chest.
        /// </summary>
        public static string lblShopAvatarEpicTitle {
            get {
                return ResourceManager.GetString("lblShopAvatarEpicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound.
        /// </summary>
        public static string lblSound {
            get {
                return ResourceManager.GetString("lblSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special tiles.
        /// </summary>
        public static string lblSpecialTilesText {
            get {
                return ResourceManager.GetString("lblSpecialTilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Statistics.
        /// </summary>
        public static string lblStatsSectionTitle {
            get {
                return ResourceManager.GetString("lblStatsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 150 coins.
        /// </summary>
        public static string lblStickerCommonPrice {
            get {
                return ResourceManager.GetString("lblStickerCommonPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 300 coins.
        /// </summary>
        public static string lblStickerEpicPrice {
            get {
                return ResourceManager.GetString("lblStickerEpicPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epic sticker chest.
        /// </summary>
        public static string lblStickerEpicText {
            get {
                return ResourceManager.GetString("lblStickerEpicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stickers.
        /// </summary>
        public static string lblStickersText {
            get {
                return ResourceManager.GetString("lblStickersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store.
        /// </summary>
        public static string lblStore {
            get {
                return ResourceManager.GetString("lblStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert the verification code.
        /// </summary>
        public static string lblVerificationMessageText {
            get {
                return ResourceManager.GetString("lblVerificationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to the game.
        /// </summary>
        public static string lblWelcomeText {
            get {
                return ResourceManager.GetString("lblWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Win Rate.
        /// </summary>
        public static string lblWinPercentage {
            get {
                return ResourceManager.GetString("lblWinPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of games.
        /// </summary>
        public static string listOfGamesTittle {
            get {
                return ResourceManager.GetString("listOfGamesTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete account.
        /// </summary>
        public static string menuDeleteAccountText {
            get {
                return ResourceManager.GetString("menuDeleteAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit account.
        /// </summary>
        public static string menuEditAccountText {
            get {
                return ResourceManager.GetString("menuEditAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View my stats.
        /// </summary>
        public static string menuViewStatsText {
            get {
                return ResourceManager.GetString("menuViewStatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report reason description.
        /// </summary>
        public static string OtherReasonDescriptionLabel {
            get {
                return ResourceManager.GetString("OtherReasonDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other reason .
        /// </summary>
        public static string OtherReasonWindowTitle {
            get {
                return ResourceManager.GetString("OtherReasonWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string pwdPasswordText {
            get {
                return ResourceManager.GetString("pwdPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason for the report.
        /// </summary>
        public static string ReasonForReportText {
            get {
                return ResourceManager.GetString("ReasonForReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have already reported this player recently. Please wait for the sanction to be processed before reporting again..
        /// </summary>
        public static string ReportErrorDuplicate {
            get {
                return ResourceManager.GetString("ReportErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The report request is invalid. Please try again..
        /// </summary>
        public static string ReportErrorInvalidRequest {
            get {
                return ResourceManager.GetString("ReportErrorInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The report could not be processed because the player information is invalid..
        /// </summary>
        public static string ReportErrorInvalidUser {
            get {
                return ResourceManager.GetString("ReportErrorInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while processing your report. Please try again..
        /// </summary>
        public static string ReportGenericErrorMessage {
            get {
                return ResourceManager.GetString("ReportGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report reason.
        /// </summary>
        public static string reportReasonWindowTitle {
            get {
                return ResourceManager.GetString("reportReasonWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report user.
        /// </summary>
        public static string reportUserTittle {
            get {
                return ResourceManager.GetString("reportUserTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dice 1–3: Only rolls values from 1 to 3.
        /// </summary>
        public static string ShopDice123Info {
            get {
                return ResourceManager.GetString("ShopDice123Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dice 4–6: Only rolls values from 4 to 6.
        /// </summary>
        public static string ShopDice456Info {
            get {
                return ResourceManager.GetString("ShopDice456Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative dice: Increases chance of going backwards.
        /// </summary>
        public static string ShopDiceNegativeInfo {
            get {
                return ResourceManager.GetString("ShopDiceNegativeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested dice was not found.
        /// </summary>
        public static string ShopDiceNotFoundWarn {
            get {
                return ResourceManager.GetString("ShopDiceNotFoundWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have enough coins for this purchase.
        /// </summary>
        public static string ShopInsufficientCoinsWarn {
            get {
                return ResourceManager.GetString("ShopInsufficientCoinsWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid dice.
        /// </summary>
        public static string ShopInvalidDiceError {
            get {
                return ResourceManager.GetString("ShopInvalidDiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid session. Please sign in again.
        /// </summary>
        public static string ShopInvalidSessionError {
            get {
                return ResourceManager.GetString("ShopInvalidSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid user.
        /// </summary>
        public static string ShopInvalidUserIdError {
            get {
                return ResourceManager.GetString("ShopInvalidUserIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item chest: Random mix of power-ups, you have chance of shields, boosts and traps.
        /// </summary>
        public static string ShopItemChestInfo {
            get {
                return ResourceManager.GetString("ShopItemChestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested item was not found.
        /// </summary>
        public static string ShopItemNotFoundWarn {
            get {
                return ResourceManager.GetString("ShopItemNotFoundWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no skins available for that rarity.
        /// </summary>
        public static string ShopNoAvatarsForRarityWarn {
            get {
                return ResourceManager.GetString("ShopNoAvatarsForRarityWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no sticker packs available.
        /// </summary>
        public static string ShopNoStickerPacksWarn {
            get {
                return ResourceManager.GetString("ShopNoStickerPacksWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A server error occurred in the shop.
        /// </summary>
        public static string ShopServerError {
            get {
                return ResourceManager.GetString("ShopServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error occurred in the shop.
        /// </summary>
        public static string ShopUnknownError {
            get {
                return ResourceManager.GetString("ShopUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.
        /// </summary>
        public static string ShopUserNotFoundError {
            get {
                return ResourceManager.GetString("ShopUserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Common sticker chest.
        /// </summary>
        public static string stickerCommonTitle {
            get {
                return ResourceManager.GetString("stickerCommonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price: 600 coins.
        /// </summary>
        public static string StickerLegendaryPrice {
            get {
                return ResourceManager.GetString("StickerLegendaryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legendary sticker chest.
        /// </summary>
        public static string StickerLegendaryText {
            get {
                return ResourceManager.GetString("StickerLegendaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stickers.
        /// </summary>
        public static string StickerSectionTitle {
            get {
                return ResourceManager.GetString("StickerSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation completed successfully..
        /// </summary>
        public static string String1AuthOk {
            get {
                return ResourceManager.GetString("String1AuthOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        public static string tvFriendsListText {
            get {
                return ResourceManager.GetString("tvFriendsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a message....
        /// </summary>
        public static string txtChatMessageText {
            get {
                return ResourceManager.GetString("txtChatMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        public static string txtLastNameOfUserText {
            get {
                return ResourceManager.GetString("txtLastNameOfUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string txtNameOfUserText {
            get {
                return ResourceManager.GetString("txtNameOfUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string txtRegEmailText {
            get {
                return ResourceManager.GetString("txtRegEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string txtUsernameText {
            get {
                return ResourceManager.GetString("txtUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account &quot;{0}&quot; has been created successfully..
        /// </summary>
        public static string UiAccountCreatedFmt {
            get {
                return ResourceManager.GetString("UiAccountCreatedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code has expired. Please request a new one.
        /// </summary>
        public static string UiChangePasswordCodeExpired {
            get {
                return ResourceManager.GetString("UiChangePasswordCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The verification code is not valid.
        /// </summary>
        public static string UiChangePasswordCodeInvalid {
            get {
                return ResourceManager.GetString("UiChangePasswordCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must request a verification code before changing your password.
        /// </summary>
        public static string UiChangePasswordCodeNotRequested {
            get {
                return ResourceManager.GetString("UiChangePasswordCodeNotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification code was sent to your email.
        /// </summary>
        public static string UiChangePasswordCodeSent {
            get {
                return ResourceManager.GetString("UiChangePasswordCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while changing your password.
        /// </summary>
        public static string UiChangePasswordGenericError {
            get {
                return ResourceManager.GetString("UiChangePasswordGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password is incorrect.
        /// </summary>
        public static string UiChangePasswordInvalidCurrent {
            get {
                return ResourceManager.GetString("UiChangePasswordInvalidCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password and confirmation do not match.
        /// </summary>
        public static string UiChangePasswordPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("UiChangePasswordPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password cannot be the same as your 3 previous passwords.
        /// </summary>
        public static string UiChangePasswordReusedPassword {
            get {
                return ResourceManager.GetString("UiChangePasswordReusedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been updated successfully.
        /// </summary>
        public static string UiChangePasswordSuccess {
            get {
                return ResourceManager.GetString("UiChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password does not meet the security requirements.
        /// </summary>
        public static string UiChangePasswordWeakPassword {
            get {
                return ResourceManager.GetString("UiChangePasswordWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email..
        /// </summary>
        public static string UiEmailInvalid {
            get {
                return ResourceManager.GetString("UiEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is required..
        /// </summary>
        public static string UiEmailRequired {
            get {
                return ResourceManager.GetString("UiEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address cannot be longer than 200 characters..
        /// </summary>
        public static string UiEmailTooLong {
            get {
                return ResourceManager.GetString("UiEmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server not found. .
        /// </summary>
        public static string UiEndpointNotFound {
            get {
                return ResourceManager.GetString("UiEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name can only contain letters..
        /// </summary>
        public static string UiFirstNameLettersOnly {
            get {
                return ResourceManager.GetString("UiFirstNameLettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name is required..
        /// </summary>
        public static string UiFirstNameRequired {
            get {
                return ResourceManager.GetString("UiFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name cannot be longer than 90 characters..
        /// </summary>
        public static string UiFirstNameTooLong {
            get {
                return ResourceManager.GetString("UiFirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred:.
        /// </summary>
        public static string UiGenericError {
            get {
                return ResourceManager.GetString("UiGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or email is required..
        /// </summary>
        public static string UiIdentifierRequired {
            get {
                return ResourceManager.GetString("UiIdentifierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or email is too long..
        /// </summary>
        public static string UiIdentifierTooLong {
            get {
                return ResourceManager.GetString("UiIdentifierTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or email is too short..
        /// </summary>
        public static string UiIdentifierTooShort {
            get {
                return ResourceManager.GetString("UiIdentifierTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name can only contain letters..
        /// </summary>
        public static string UiLastNameLettersOnly {
            get {
                return ResourceManager.GetString("UiLastNameLettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name is required..
        /// </summary>
        public static string UiLastNameRequired {
            get {
                return ResourceManager.GetString("UiLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name cannot be longer than 90 characters..
        /// </summary>
        public static string UiLastNameTooLong {
            get {
                return ResourceManager.GetString("UiLastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login successful. Welcome!.
        /// </summary>
        public static string UiLoginOk {
            get {
                return ResourceManager.GetString("UiLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name is required..
        /// </summary>
        public static string UiNameRequired {
            get {
                return ResourceManager.GetString("UiNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No previous page..
        /// </summary>
        public static string UiNoBackPage {
            get {
                return ResourceManager.GetString("UiNoBackPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least 8 characters, one uppercase letter, one lowercase letter, and one special character..
        /// </summary>
        public static string UiPasswordPolicyDescription {
            get {
                return ResourceManager.GetString("UiPasswordPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is required..
        /// </summary>
        public static string UiPasswordRequired {
            get {
                return ResourceManager.GetString("UiPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too long.
        /// </summary>
        public static string UiPasswordTooLong {
            get {
                return ResourceManager.GetString("UiPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password: at least 8 characters..
        /// </summary>
        public static string UiPasswordTooShort {
            get {
                return ResourceManager.GetString("UiPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend in {0}s.
        /// </summary>
        public static string UiResendCodeInFmt {
            get {
                return ResourceManager.GetString("UiResendCodeInFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session started, but the service did not return a token. Some features may not be available..
        /// </summary>
        public static string UiSessionTokenMissingWarn {
            get {
                return ResourceManager.GetString("UiSessionTokenMissingWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chest details.
        /// </summary>
        public static string UiShopChestInfoTitle {
            get {
                return ResourceManager.GetString("UiShopChestInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You obtained: {0}. Current coins: {1}.
        /// </summary>
        public static string UiShopPurchaseSuccessFmt {
            get {
                return ResourceManager.GetString("UiShopPurchaseSuccessFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must sign in to use the shop.
        /// </summary>
        public static string UiShopRequiresLogin {
            get {
                return ResourceManager.GetString("UiShopRequiresLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The shop is only available for registered accounts..
        /// </summary>
        public static string UiShopRequiresRegisteredUser {
            get {
                return ResourceManager.GetString("UiShopRequiresRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session token is missing. Please sign in again.
        /// </summary>
        public static string UiShopRequiresToken {
            get {
                return ResourceManager.GetString("UiShopRequiresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string UiTitleError {
            get {
                return ResourceManager.GetString("UiTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string UiTitleInfo {
            get {
                return ResourceManager.GetString("UiTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string UiTitleWarning {
            get {
                return ResourceManager.GetString("UiTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error occurred while navigating..
        /// </summary>
        public static string UiUnexpectedNavigationError {
            get {
                return ResourceManager.GetString("UiUnexpectedNavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is required.
        /// </summary>
        public static string UiUserNameRequired {
            get {
                return ResourceManager.GetString("UiUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username cannot be longer than 90 characters..
        /// </summary>
        public static string UiUserNameTooLong {
            get {
                return ResourceManager.GetString("UiUserNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code is required..
        /// </summary>
        public static string UiVerificationCodeRequired {
            get {
                return ResourceManager.GetString("UiVerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification email was sent to {0}..
        /// </summary>
        public static string UiVerificationSentFmt {
            get {
                return ResourceManager.GetString("UiVerificationSentFmt", resourceCulture);
            }
        }
    }
}
