//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeAndLaddersFinalProject.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnakeAndLaddersFinalProject.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string bntContinueText {
            get {
                return ResourceManager.GetString("bntContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friend.
        /// </summary>
        internal static string bntInviteFriendText {
            get {
                return ResourceManager.GetString("bntInviteFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string btnAcceptText {
            get {
                return ResourceManager.GetString("btnAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        internal static string btnAddFriendText {
            get {
                return ResourceManager.GetString("btnAddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string btnBackText {
            get {
                return ResourceManager.GetString("btnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Match.
        /// </summary>
        internal static string btnCreateMatchText {
            get {
                return ResourceManager.GetString("btnCreateMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exploiting.
        /// </summary>
        internal static string btnExploitingText {
            get {
                return ResourceManager.GetString("btnExploitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        internal static string btnFriendsText {
            get {
                return ResourceManager.GetString("btnFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Harassment.
        /// </summary>
        internal static string btnHarassmentText {
            get {
                return ResourceManager.GetString("btnHarassmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inappropriate language.
        /// </summary>
        internal static string btnInappropiateLangText {
            get {
                return ResourceManager.GetString("btnInappropiateLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        internal static string btnInventoryText {
            get {
                return ResourceManager.GetString("btnInventoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        internal static string btnJoinMatchText {
            get {
                return ResourceManager.GetString("btnJoinMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other....
        /// </summary>
        internal static string btnOtherReasonText {
            get {
                return ResourceManager.GetString("btnOtherReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string btnProfileText {
            get {
                return ResourceManager.GetString("btnProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string btnSettingsText {
            get {
                return ResourceManager.GetString("btnSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shop.
        /// </summary>
        internal static string btnShopText {
            get {
                return ResourceManager.GetString("btnShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        internal static string btnSignUpText {
            get {
                return ResourceManager.GetString("btnSignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skins.
        /// </summary>
        internal static string btnSkinsText {
            get {
                return ResourceManager.GetString("btnSkinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toxic behavior.
        /// </summary>
        internal static string btnToxicBehaviorText {
            get {
                return ResourceManager.GetString("btnToxicBehaviorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unfriend.
        /// </summary>
        internal static string btnUnfriendText {
            get {
                return ResourceManager.GetString("btnUnfriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This character cries when she has an exam.
        /// </summary>
        internal static string character1DescriptionText {
            get {
                return ResourceManager.GetString("character1DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        internal static string chatTittle {
            get {
                return ResourceManager.GetString("chatTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friends.
        /// </summary>
        internal static string lblAddFriends {
            get {
                return ResourceManager.GetString("lblAddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character description.
        /// </summary>
        internal static string lblcharacterDescriptionText {
            get {
                return ResourceManager.GetString("lblcharacterDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coins.
        /// </summary>
        internal static string lblCoinsText {
            get {
                return ResourceManager.GetString("lblCoinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find friends.
        /// </summary>
        internal static string lblFindFriensText {
            get {
                return ResourceManager.GetString("lblFindFriensText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find match.
        /// </summary>
        internal static string lblFindMatchText {
            get {
                return ResourceManager.GetString("lblFindMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new account.
        /// </summary>
        internal static string lblRegisterTitle {
            get {
                return ResourceManager.GetString("lblRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stickers.
        /// </summary>
        internal static string lblStickersText {
            get {
                return ResourceManager.GetString("lblStickersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of games.
        /// </summary>
        internal static string listOfGamesTittle {
            get {
                return ResourceManager.GetString("listOfGamesTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string pwdPasswordTex {
            get {
                return ResourceManager.GetString("pwdPasswordTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report user.
        /// </summary>
        internal static string reportUserTittle {
            get {
                return ResourceManager.GetString("reportUserTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        internal static string tvFriendsListText {
            get {
                return ResourceManager.GetString("tvFriendsListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a message....
        /// </summary>
        internal static string txtChatMessageText {
            get {
                return ResourceManager.GetString("txtChatMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastname.
        /// </summary>
        internal static string txtLastNameOfUserText {
            get {
                return ResourceManager.GetString("txtLastNameOfUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string txtNameOfUserText {
            get {
                return ResourceManager.GetString("txtNameOfUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string txtRegEmailText {
            get {
                return ResourceManager.GetString("txtRegEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string txtUsernameText {
            get {
                return ResourceManager.GetString("txtUsernameText", resourceCulture);
            }
        }
    }
}
